## Server Config
server:
  port: 8080

## DB Connection
spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_URL}/subscription
    username: ${DB_USERNAME}

## JWT Config
jwt:
  secret: javainuse
  get:
    token:
      uri: /authenticate
